# .github/workflows/sonar.yml
name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: java_build
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=chai-git-bit_DevSecops_Pipeline -Dsonar.organization=chai-git-bit -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=dbb609329cf31067526298cda5f7fd24feb1c00f
