# .github/workflows/test.yml
name: Test

on:
  workflow_call:

jobs:
  test:
    runs-on: self_hosted
    #needs: build  # Ensures test only runs after build succeeds
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Install Maven
        run: sudo apt update && sudo apt install -y maven

      - name: Run Unit Tests
        run: mvn test

      # - name: Upload Test Results h
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: target/test-classes/TEST-*.xml
